// Demo opportunity catalog. Content slice.
//
// EVERY entry here is a placeholder (isSample: true). Organisations and URLs are
// invented so nothing in the demo can be mistaken for a real listing. Replace
// with hand-verified listings and set isSample: false as they are confirmed.
//
// Event and deadline dates are computed relative to today so the demo never goes
// stale. A few entries are deliberately in the past to exercise the "hide past
// events / expired deadlines" rule.

import type { Opportunity, PreferenceTrait, RiasecCode } from '../models';

const DAY_MS = 24 * 60 * 60 * 1000;

function daysFromNow(days: number, hour = 0): string {
  const date = new Date(Date.now() + days * DAY_MS);
  date.setUTCHours(hour, 0, 0, 0);
  return date.toISOString();
}

function dateFromNow(days: number): string {
  return daysFromNow(days).slice(0, 10);
}

/** Trait scores in the same order as the priority budget, to keep entries short. */
function traits(
  pay: number,
  flexibility: number,
  growth: number,
  mission: number,
  people: number,
  manager: number,
  autonomy: number,
): Record<PreferenceTrait, number> {
  return {
    pay_and_security: pay,
    flexibility_and_balance: flexibility,
    growth_and_learning: growth,
    mission_and_impact: mission,
    people_and_team: people,
    manager_support: manager,
    autonomy,
  };
}

const VERIFIED = dateFromNow(0);
const SAMPLE_URL = 'https://example.com/sample-opportunity';
const holland = (...codes: RiasecCode[]): RiasecCode[] => codes;

export const OPPORTUNITIES: Opportunity[] = [
  // ---- Jobs and internships ------------------------------------------------
  {
    id: 'job-junior-web-dev',
    kind: 'job',
    title: 'Junior Web Developer',
    organization: 'Northwind Digital (sample)',
    summary: 'Build and fix customer-facing pages on a small product team, with a senior mentor.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    hollandCode: holland('I', 'R', 'C'),
    traits: traits(75, 60, 85, 45, 65, 80, 55),
    jobZone: 3,
    minEducation: 'certificate',
    suitableStages: ['FirstRole', 'EarlyCareer', 'Pivot'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    employmentType: 'FullTime',
    payMinUsd: 62000,
    payMaxUsd: 78000,
    applyBy: dateFromNow(40),
  },
  {
    id: 'job-ux-intern',
    kind: 'job',
    title: 'UX Design Intern',
    organization: 'Harbor Studio (sample)',
    summary: 'Sketch, test and iterate on app flows alongside a design lead. Paid, three months.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('A', 'I', 'S'),
    traits: traits(45, 85, 90, 55, 70, 85, 60),
    jobZone: 2,
    minEducation: 'secondary',
    suitableStages: ['FirstRole', 'Pivot', 'Returner'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    employmentType: 'Internship',
    payMinUsd: 28000,
    payMaxUsd: 34000,
    applyBy: dateFromNow(21),
  },
  {
    id: 'job-electrician-apprentice',
    kind: 'job',
    title: 'Electrical Apprentice',
    organization: 'Summit Trades Alliance (sample)',
    summary: 'Paid on-the-job training toward a journey-level license, with classroom hours built in.',
    url: SAMPLE_URL,
    location: 'Tacoma, WA',
    arrangement: 'Onsite',
    hollandCode: holland('R', 'C', 'I'),
    traits: traits(80, 35, 80, 50, 70, 75, 40),
    jobZone: 2,
    minEducation: 'secondary',
    suitableStages: ['FirstRole', 'Pivot', 'EarlyCareer'],
    demands: ['physical_work'],
    verifiedOn: VERIFIED,
    isSample: true,
    employmentType: 'Apprenticeship',
    payMinUsd: 46000,
    payMaxUsd: 60000,
    applyBy: null,
  },
  {
    id: 'job-community-outreach',
    kind: 'job',
    title: 'Community Outreach Coordinator',
    organization: 'Bridgeway Nonprofit (sample)',
    summary: 'Connect residents to job and housing services; run small events and follow up one-on-one.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    hollandCode: holland('S', 'E', 'A'),
    traits: traits(55, 65, 60, 95, 90, 70, 60),
    jobZone: 3,
    minEducation: 'associate',
    suitableStages: ['EarlyCareer', 'MidCareer', 'Pivot', 'Returner'],
    demands: ['night_shifts'],
    verifiedOn: VERIFIED,
    isSample: true,
    employmentType: 'FullTime',
    payMinUsd: 52000,
    payMaxUsd: 64000,
    applyBy: dateFromNow(30),
  },
  {
    id: 'job-data-analyst',
    kind: 'job',
    title: 'Data Analyst',
    organization: 'Meridian Health Systems (sample)',
    summary: 'Turn clinic scheduling data into weekly reports and answer questions from operations.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('I', 'C', 'E'),
    traits: traits(85, 85, 70, 65, 50, 60, 75),
    jobZone: 4,
    minEducation: 'bachelor',
    suitableStages: ['EarlyCareer', 'MidCareer', 'Pivot'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    employmentType: 'FullTime',
    payMinUsd: 78000,
    payMaxUsd: 96000,
    applyBy: dateFromNow(25),
  },
  {
    id: 'job-sales-associate',
    kind: 'job',
    title: 'Account Executive',
    organization: 'Copperline Software (sample)',
    summary: 'Own a book of small-business accounts. Commission on top of base, quota-driven.',
    url: SAMPLE_URL,
    location: 'Bellevue, WA',
    arrangement: 'Hybrid',
    hollandCode: holland('E', 'S', 'C'),
    traits: traits(90, 45, 70, 30, 70, 50, 70),
    jobZone: 3,
    minEducation: 'bachelor',
    suitableStages: ['EarlyCareer', 'MidCareer', 'SteppingUp'],
    demands: ['sales_targets', 'heavy_travel'],
    verifiedOn: VERIFIED,
    isSample: true,
    employmentType: 'FullTime',
    payMinUsd: 70000,
    payMaxUsd: 140000,
    applyBy: null,
  },

  // ---- Programs ------------------------------------------------------------
  {
    id: 'program-coding-bootcamp',
    kind: 'program',
    title: 'Full-Stack Coding Program',
    organization: 'Lakeside Tech Academy (sample)',
    summary: 'Nine-month, tuition-free cohort program with paid placement support for career changers.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    hollandCode: holland('I', 'R', 'A'),
    traits: traits(60, 55, 95, 65, 85, 80, 50),
    jobZone: 3,
    minEducation: 'secondary',
    suitableStages: ['FirstRole', 'Pivot', 'Returner', 'EarlyCareer'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    costUsd: 0,
    stipendUsd: null,
    durationWeeks: 36,
    startsAt: dateFromNow(75),
    applyBy: dateFromNow(35),
    eligibility: ['Open to adults changing careers', 'Basic computer skills'],
  },
  {
    id: 'program-data-certificate',
    kind: 'program',
    title: 'Data Skills Certificate',
    organization: 'Riverbend Community College (sample)',
    summary: 'Part-time evening certificate in spreadsheets, SQL and dashboards. Finish in two terms.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('I', 'C'),
    traits: traits(70, 90, 85, 40, 45, 60, 65),
    jobZone: 3,
    minEducation: 'secondary',
    suitableStages: ['EarlyCareer', 'MidCareer', 'Pivot', 'Returner'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    costUsd: 1800,
    stipendUsd: null,
    durationWeeks: 20,
    startsAt: dateFromNow(50),
    applyBy: dateFromNow(30),
    eligibility: ['No prior experience needed'],
  },
  {
    id: 'program-paid-trades-cohort',
    kind: 'program',
    title: 'Pre-Apprenticeship Trades Cohort',
    organization: 'Summit Trades Alliance (sample)',
    summary: 'Twelve paid weeks trying several trades, ending with a guaranteed apprenticeship interview.',
    url: SAMPLE_URL,
    location: 'Tacoma, WA',
    arrangement: 'Onsite',
    hollandCode: holland('R', 'C', 'S'),
    traits: traits(65, 30, 85, 55, 80, 80, 35),
    jobZone: 2,
    minEducation: 'none_required',
    suitableStages: ['FirstRole', 'Pivot', 'Returner'],
    demands: ['physical_work'],
    verifiedOn: VERIFIED,
    isSample: true,
    costUsd: 0,
    stipendUsd: 9000,
    durationWeeks: 12,
    startsAt: dateFromNow(45),
    applyBy: dateFromNow(20),
    eligibility: ['Ages 18 and up'],
  },
  {
    id: 'program-leadership-fellowship',
    kind: 'program',
    title: 'Emerging Leaders Fellowship',
    organization: 'Commonground Foundation (sample)',
    summary: 'Six-month cohort with a mentor, a small grant and a capstone project for people moving into management.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    hollandCode: holland('E', 'S', 'A'),
    traits: traits(55, 60, 90, 85, 90, 90, 60),
    jobZone: 4,
    minEducation: 'associate',
    suitableStages: ['MidCareer', 'SteppingUp'],
    demands: ['managing_people'],
    verifiedOn: VERIFIED,
    isSample: true,
    costUsd: 0,
    stipendUsd: 2500,
    durationWeeks: 26,
    startsAt: dateFromNow(60),
    applyBy: dateFromNow(28),
    eligibility: ['Three or more years of work experience'],
  },
  {
    id: 'program-returnship',
    kind: 'program',
    title: 'Returnship for Career Returners',
    organization: 'Meridian Health Systems (sample)',
    summary: 'A paid sixteen-week re-entry placement with coaching for people back after a career break.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('C', 'E', 'S'),
    traits: traits(75, 90, 75, 55, 75, 90, 55),
    jobZone: 3,
    minEducation: 'associate',
    suitableStages: ['Returner'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    costUsd: 0,
    stipendUsd: 12000,
    durationWeeks: 16,
    startsAt: dateFromNow(55),
    applyBy: dateFromNow(32),
    eligibility: ['Out of the workforce for two or more years'],
  },

  // ---- Events --------------------------------------------------------------
  {
    id: 'event-networking-mixer',
    kind: 'event',
    title: 'Career Changers Networking Mixer',
    organization: 'Local Tech Meetup (sample)',
    summary: 'Casual evening for people switching fields. Short lightning talks, then open mingling.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Onsite',
    hollandCode: holland('S', 'E'),
    traits: traits(30, 60, 65, 50, 95, 45, 70),
    jobZone: null,
    minEducation: 'none_required',
    suitableStages: ['Pivot', 'EarlyCareer', 'Returner'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    format: 'networking',
    startsAt: daysFromNow(9, 1),
    endsAt: daysFromNow(9, 4),
    costUsd: 0,
  },
  {
    id: 'event-resume-workshop',
    kind: 'event',
    title: 'Resume and Portfolio Workshop',
    organization: 'Bridgeway Nonprofit (sample)',
    summary: 'Ninety minutes of hands-on feedback on your resume, with a volunteer hiring manager.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('C', 'E', 'S'),
    traits: traits(45, 90, 85, 50, 60, 85, 40),
    jobZone: null,
    minEducation: 'none_required',
    suitableStages: [],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    format: 'workshop',
    startsAt: daysFromNow(4, 18),
    endsAt: daysFromNow(4, 19),
    costUsd: 0,
  },
  {
    id: 'event-intro-to-sql',
    kind: 'event',
    title: 'Intro to SQL: One-Day Skills Workshop',
    organization: 'Riverbend Community College (sample)',
    summary: 'Write your first queries against a real dataset. Laptop required, no experience needed.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Onsite',
    hollandCode: holland('I', 'C'),
    traits: traits(40, 50, 95, 35, 60, 70, 55),
    jobZone: null,
    minEducation: 'none_required',
    suitableStages: ['FirstRole', 'Pivot', 'EarlyCareer'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    format: 'workshop',
    startsAt: daysFromNow(16, 16),
    endsAt: daysFromNow(16, 23),
    costUsd: 40,
  },
  {
    id: 'event-trades-open-house',
    kind: 'event',
    title: 'Skilled Trades Open House',
    organization: 'Summit Trades Alliance (sample)',
    summary: 'Tour the training facility, try welding and wiring stations, and talk to current apprentices.',
    url: SAMPLE_URL,
    location: 'Tacoma, WA',
    arrangement: 'Onsite',
    hollandCode: holland('R', 'C'),
    traits: traits(70, 30, 70, 50, 85, 70, 40),
    jobZone: null,
    minEducation: 'none_required',
    suitableStages: [],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    format: 'career_fair',
    startsAt: daysFromNow(12, 17),
    endsAt: daysFromNow(12, 21),
    costUsd: 0,
  },
  {
    id: 'event-design-talk',
    kind: 'event',
    title: 'Breaking Into Design: A Panel',
    organization: 'Harbor Studio (sample)',
    summary: 'Four designers talk about how they got their first role and what they would do differently.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('A', 'S', 'E'),
    traits: traits(35, 90, 80, 55, 75, 55, 55),
    jobZone: null,
    minEducation: 'none_required',
    suitableStages: ['FirstRole', 'Pivot', 'EarlyCareer'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    format: 'talk',
    startsAt: daysFromNow(6, 1),
    endsAt: null,
    costUsd: 0,
  },
  {
    id: 'event-past-career-fair',
    kind: 'event',
    title: 'Spring Career Fair',
    organization: 'Regional Workforce Board (sample)',
    summary: 'Already happened. Present so the hide-past-events rule has something to hide.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Onsite',
    hollandCode: holland('E', 'S'),
    traits: traits(60, 50, 60, 50, 90, 50, 50),
    jobZone: null,
    minEducation: 'none_required',
    suitableStages: [],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    format: 'career_fair',
    startsAt: daysFromNow(-10, 16),
    endsAt: daysFromNow(-10, 20),
    costUsd: 0,
  },

  // ---- Research programs ---------------------------------------------------
  {
    id: 'research-hci-summer',
    kind: 'research',
    title: 'Human-Computer Interaction Research Fellowship',
    organization: 'State University Lab (sample)',
    summary: 'Ten weeks running user studies with a faculty mentor, ending in a poster presentation.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Onsite',
    hollandCode: holland('I', 'A', 'S'),
    traits: traits(55, 55, 95, 65, 70, 90, 60),
    jobZone: 4,
    minEducation: 'secondary',
    suitableStages: ['FirstRole', 'EarlyCareer', 'Pivot'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    field: 'Human-computer interaction',
    stipendUsd: 6000,
    durationWeeks: 10,
    startsAt: dateFromNow(100),
    applyBy: dateFromNow(45),
    eligibility: ['Enrolled in or recently finished a degree program'],
  },
  {
    id: 'research-public-health',
    kind: 'research',
    title: 'Community Health Research Assistant',
    organization: 'Meridian Health Systems (sample)',
    summary: 'Help collect and analyse survey data on neighbourhood health access. Part-time, remote-friendly.',
    url: SAMPLE_URL,
    location: null,
    arrangement: 'Remote',
    hollandCode: holland('I', 'S', 'C'),
    traits: traits(50, 90, 80, 90, 70, 75, 60),
    jobZone: 3,
    minEducation: 'associate',
    suitableStages: ['FirstRole', 'EarlyCareer', 'Pivot', 'Returner'],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    field: 'Public health',
    stipendUsd: 4500,
    durationWeeks: 16,
    startsAt: dateFromNow(60),
    applyBy: dateFromNow(30),
    eligibility: ['Comfortable with spreadsheets'],
  },
  {
    id: 'research-materials-lab',
    kind: 'research',
    title: 'Materials Science Lab Technician Program',
    organization: 'Institute of Applied Science (sample)',
    summary: 'Hands-on sample prep and testing in a working lab. Paid, with a path to a technician role.',
    url: SAMPLE_URL,
    location: 'Tacoma, WA',
    arrangement: 'Onsite',
    hollandCode: holland('R', 'I', 'C'),
    traits: traits(65, 40, 80, 60, 55, 75, 45),
    jobZone: 3,
    minEducation: 'certificate',
    suitableStages: ['FirstRole', 'Pivot', 'EarlyCareer'],
    demands: ['physical_work'],
    verifiedOn: VERIFIED,
    isSample: true,
    field: 'Materials science',
    stipendUsd: 8000,
    durationWeeks: 20,
    startsAt: dateFromNow(80),
    applyBy: dateFromNow(38),
    eligibility: ['Basic lab or trade experience helpful'],
  },
  {
    id: 'research-past-deadline',
    kind: 'research',
    title: 'Behavioral Economics Summer Program',
    organization: 'State University Lab (sample)',
    summary: 'Application closed. Present so the expired-deadline rule has something to hide.',
    url: SAMPLE_URL,
    location: 'Seattle, WA',
    arrangement: 'Onsite',
    hollandCode: holland('I', 'E', 'C'),
    traits: traits(55, 50, 90, 55, 60, 80, 60),
    jobZone: 4,
    minEducation: 'bachelor',
    suitableStages: [],
    demands: [],
    verifiedOn: VERIFIED,
    isSample: true,
    field: 'Behavioral economics',
    stipendUsd: 7000,
    durationWeeks: 8,
    startsAt: dateFromNow(30),
    applyBy: dateFromNow(-5),
    eligibility: [],
  },
];
