// The curated registry: one entry per research programme in metro Detroit that
// a person can actually apply to.
//
// Why a registry and not a scraper. Almost no university or hospital publishes
// research programmes as a feed. There is no equivalent of the events
// pipeline's tribe/ics endpoints: the NSF's own REU search sits behind an AWS
// WAF challenge, umich.edu answers robots with a Cloudflare challenge, and
// Pathways to Science renders its results through ASP.NET postbacks. Pretending
// otherwise would mean an adapter that silently returns nothing.
//
// So the facts below were read off the public page by a human, and the pipeline
// takes over from there: every run re-fetches each url, records whether it is
// still reachable, re-reads the numbers with scripts/research/extract.ts and
// reports anything that no longer matches. Stale entries surface in the run
// report instead of rotting quietly.
//
// House rules for adding one:
//   - `url` must be the page you actually read, and must return 200.
//   - stipendUsd / durationWeeks / applyBy / startsAt come off that page. If the
//     page does not say, the value is null. Never a guess, never a typical value.
//   - a deadline stated without a year ("applications are due February 15") goes
//     in annualDeadline as 'MM-DD', not in applyBy.
//   - minEducation is the floor to take part. A programme that requires current
//     undergraduate enrolment is 'secondary', never 'none_required'; the real
//     constraint rides in enrollmentRequired.
//   - `notes` is for anything a human should know that the fields cannot hold.

import type { EducationLevel } from '../../src/models';
import type {
  ApplicationMethod,
  CitizenshipRequirement,
  EnrollmentRequirement,
  FactsSource,
  MentorshipModel,
  Recurrence,
} from './types';

export type RegistryEntry = {
  /** Stable slug. Becomes part of the opportunity id, so never rename one. */
  key: string;
  title: string;
  /** Who runs it, as shown on the card. */
  organization: string;
  institution: string;
  /** The page the facts were read from. Re-checked every run. */
  url: string;
  /** Metro city, or null when remote or unstated. */
  city: string | null;
  isOnline?: boolean;
  /** One or two sentences, drawn from the page. */
  summary: string;
  field: string;
  disciplines: string[];

  stipendUsd: number | null;
  durationWeeks: number | null;
  startsAt: string | null;
  applyBy: string | null;
  /** 'MM-DD' for a deadline the page states without a year. */
  annualDeadline?: string | null;
  eligibility: string[];

  minEducation: EducationLevel;
  enrollmentRequired: EnrollmentRequirement;
  citizenship: CitizenshipRequirement;
  isPaid: boolean | null;
  mentorshipModel: MentorshipModel;
  applicationMethod: ApplicationMethod;
  recurrence: Recurrence;
  nextWindowOpens?: string | null;
  communityBased: boolean;
  /** Reachable with no degree and no current enrolment. The app's hardest need. */
  lowBarrier: boolean;
  factsFrom: FactsSource;
  /** Ties the entry to an NSF award, so discovery can top up and watch it. */
  nsfAwardId?: string;
  /** Anything a human must know. Surfaced in the run report as a drift note. */
  notes?: string[];
};

export const REGISTRY: RegistryEntry[] = [
  // ---- Wayne State University -------------------------------------------------
  {
    key: 'wsu-urop-award',
    title: 'Undergraduate Research and Creative Projects Award (UROP)',
    organization: 'Wayne State University',
    institution: 'Wayne State University',
    url: 'https://urop.wayne.edu/award',
    city: 'Detroit',
    summary:
      'A funded research or creative project carried out alongside a Wayne State faculty mentor. Open to undergraduates in any major or year of study, with two award cycles each academic year.',
    field: 'Any discipline',
    disciplines: ['interdisciplinary', 'arts', 'sciences', 'humanities'],
    stipendUsd: 2300,
    durationWeeks: null,
    startsAt: null,
    applyBy: '2026-12-01',
    eligibility: [
      'Be an undergraduate enrolled at least half-time (except during the Spring/Summer term)',
      'Any major or year of study',
      'A faculty mentor must agree to supervise the project',
      'Second cycle each year closes April 1 (Spring/Summer - Fall)',
      'Students eligible for Federal Work-Study are encouraged to use it instead of the scholarship award',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: true,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_academic_year',
    nextWindowOpens: '2026-10-01',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: ['Award is $2,300 for a full two-semester cycle, $1,150 for students graduating mid-cycle.'],
  },
  {
    key: 'wsu-surf-physiology',
    title: 'Summer Undergraduate Research Fellowship (SURF)',
    organization: 'Wayne State University Department of Physiology',
    institution: 'Wayne State University',
    url: 'https://physiology.med.wayne.edu/summer-research',
    city: 'Detroit',
    summary:
      'Full-time laboratory research training in physiology over 10 to 12 weeks of the summer, with a stipend and an introduction to graduate programs. Participants present their research at the end.',
    field: 'Physiology',
    disciplines: ['physiology', 'biomedical science', 'life sciences'],
    stipendUsd: null,
    durationWeeks: 10,
    startsAt: null,
    applyBy: '2026-02-15',
    eligibility: [
      'Undergraduate with a 3.0 GPA or better',
      'An interest in physiology',
      'Selection weighs academic achievement, commitment to basic research and mentor availability',
      'The program cannot accept international scholars at this time',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'us_work_authorized',
    isPaid: true,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: ['The page states a stipend but not an amount, so stipendUsd is null. Page says "10-12 weeks"; the low end is recorded.'],
  },
  {
    key: 'wsu-nextgen-oncology',
    title: 'NextGen Oncology Scholars Fellowship',
    organization: 'Cancer Biology Graduate Program, Wayne State University and Karmanos Cancer Institute',
    institution: 'Wayne State University',
    url: 'https://cancerbiologyprogram.med.wayne.edu/nextgenonc-application',
    city: 'Detroit',
    summary:
      'A 10-week paid summer fellowship in cancer biology. Each scholar is assigned to a faculty member, carries out a specific research project, attends a weekly course and presents a poster on Summer Research Poster Day.',
    field: 'Cancer biology',
    disciplines: ['cancer biology', 'oncology', 'biomedical science'],
    stipendUsd: null,
    durationWeeks: 10,
    startsAt: null,
    applyBy: null,
    annualDeadline: '02-15',
    eligibility: [
      'Undergraduates interested in a career in biomedical research',
      'All supporting materials must reach the program office by February 15',
      'Online application form, letter of interest, two letters of recommendation, resume and unofficial transcripts',
      'Students must work the entire 10-week period, late May to early August',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: true,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: [
      'The page says fellows "will be paid a stipend" without an amount, and states February 15 with no year, so applyBy is null and annualDeadline carries the date.',
      'Some housing support may be available.',
    ],
  },
  {
    key: 'wsu-reu-sustainable-manufacturing',
    title: 'NSF REU Site: Summer Academy in Sustainable Manufacturing',
    organization: 'Wayne State University College of Engineering',
    institution: 'Wayne State University',
    url: 'https://advancedmaterials.wayne.edu/summer-academy',
    city: 'Detroit',
    summary:
      'A 10-week NSF-funded summer research experience in sustainable manufacturing, working with Wayne State faculty and graduate students on projects that weigh the economic, environmental and social side of how things get made.',
    field: 'Sustainable manufacturing',
    disciplines: ['manufacturing', 'materials science', 'mechanical engineering', 'sustainability'],
    stipendUsd: 7000,
    durationWeeks: 10,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Must be a U.S. citizen or permanent resident',
      'Undergraduate students from any institution in the country',
      'Room and board in Wayne State dormitories is covered',
      '$500 towards travel to and from Wayne State',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'us_citizen_or_pr',
    isPaid: true,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    nsfAwardId: '2348993',
    notes: ['Stipend is stated as $700 per week for 10 weeks ($7,000 total). The page carries no application deadline.'],
  },
  {
    key: 'wsu-discovery-to-cure',
    title: 'Discovery to Cure Summer Internship',
    organization: 'C.S. Mott Center for Human Growth and Development, Wayne State University',
    institution: 'Wayne State University',
    url: 'https://mott.med.wayne.edu/discovery-to-cure-application/',
    city: 'Detroit',
    summary:
      'A summer research internship in reproductive and developmental science, running June to August. Open both to rising high school seniors and to undergraduates from any college or university.',
    field: 'Reproductive and developmental biology',
    disciplines: ['reproductive science', 'developmental biology', 'biomedical science'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'High school students: rising seniors at least 16 years of age, in the summer between junior and senior year',
      'Undergraduates: open to Wayne State and to any other college or university',
      'The program runs from June to August',
      'The program cannot provide housing or transportation',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'high_school',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: [
      'As of the last check the page says both the undergraduate and the high school applications are closed for summer 2026; it recurs each year.',
      'An acceptance letter can be issued to international students for a visa application, but the program cannot assist further.',
    ],
  },
  {
    key: 'wsu-grad-summer-research',
    title: 'Summer Research Program (SRP)',
    organization: 'Wayne State University Graduate School',
    institution: 'Wayne State University',
    url: 'https://gradschool.wayne.edu/summer-research',
    city: 'Detroit',
    summary:
      'A two-week summer program preparing students historically underserved in doctoral education for intensive research and the PhD application, in English, social work or biological sciences.',
    field: 'Doctoral preparation',
    disciplines: ['english', 'social work', 'biological sciences'],
    stipendUsd: null,
    durationWeeks: 2,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Historically underserved in doctoral education, discipline or socioeconomic status',
      'Attend a historically black college or university, or be an underrepresented minority',
      'An interest in a PhD in English, social work or biological sciences',
      'A 3.0 GPA',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'contact_program',
    recurrence: 'unknown',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: [
      'The page still describes the June 19 - July 1, 2022 cohort and says "The nomination process is currently closed". Confirm with the Graduate School that the program is still running before this is shown to anyone.',
    ],
  },
  {
    key: 'wsu-center-urban-studies',
    title: 'Center for Urban Studies research and evaluation projects',
    organization: 'Wayne State University Center for Urban Studies',
    institution: 'Wayne State University',
    url: 'https://cus.wayne.edu/research',
    city: 'Detroit',
    summary:
      'The university\'s hub for applied urban research in Detroit: early childhood and disabilities, urban safety, overdose prevention, and urban and community health. Projects hire research and outreach staff directly.',
    field: 'Urban studies',
    disciplines: ['urban studies', 'public health', 'social policy', 'program evaluation'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Openings vary by project; contact the Center for current research and evaluation roles'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'us_work_authorized',
    isPaid: true,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['A hub page rather than a single opening. Requirements differ per project and must be checked with the Center.'],
  },
  {
    key: 'amus-detroit-americorps',
    title: 'AmeriCorps Urban Safety (AMUS) member',
    organization: 'AmeriCorps Urban Safety, Wayne State University Center for Urban Studies',
    institution: 'Wayne State University',
    url: 'https://amusdetroit.org/employment/',
    city: 'Detroit',
    summary:
      'Paid AmeriCorps service with Wayne State\'s Center for Urban Studies: community organising, forming neighbourhood block clubs and citizen patrols, and public health and safety fieldwork across Detroit. Full-time and part-time positions.',
    field: 'Community health and safety',
    disciplines: ['community organising', 'public health', 'urban safety', 'field data collection'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Full-time and part-time AmeriCorps positions',
      'Monthly living allowance, plus an education award on successful completion of service',
      'Health coverage available with full-time service',
      'Child care service available for eligible members',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'us_citizen_or_pr',
    isPaid: true,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['The page describes the living allowance and education award without amounts, so stipendUsd is null.'],
  },

  // ---- Karmanos Cancer Institute ------------------------------------------------
  {
    key: 'karmanos-kcap',
    title: 'Karmanos Cancer Advocacy Program (KCAP) advocate',
    organization: 'Karmanos Cancer Institute',
    institution: 'Karmanos Cancer Institute',
    url: 'https://www.karmanos.org/karmanos/karmanos-cancer-advocacy-program',
    city: 'Detroit',
    summary:
      'Patients, family members and caregivers join the research community as cancer advocates: raising clinical trial awareness across local and state communities and providing a forum for cancer education. No academic background is asked for.',
    field: 'Cancer research advocacy',
    disciplines: ['patient advocacy', 'clinical trials', 'community engagement', 'cancer research'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'A patient, family member or caregiver with personal experience of a cancer diagnosis',
      'Demonstrated effectiveness interacting with groups as a leader or active participant',
      'Willingness to embrace a broad perspective of cancer research and training',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['The page does not say whether advocates are paid, so isPaid is null.'],
  },
  {
    key: 'karmanos-research-advisor-program',
    title: 'Research Advisor Program (RAP) community member',
    organization: 'Karmanos Cancer Institute',
    institution: 'Karmanos Cancer Institute',
    url: 'https://www.karmanos.org/karmanos/research-advisor-program',
    city: 'Detroit',
    summary:
      'Community members are built into Karmanos\' three research programs — Molecular Therapeutics, Tumor Biology and the Microenvironment, and Population Studies — each paired with a "science buddy" who helps them take part, including reviewing lay abstracts and specific aims.',
    field: 'Community-engaged cancer research',
    disciplines: ['cancer research', 'community engagement', 'research review'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Open to community stakeholders; no research background is required',
      'Each member is assigned a research programme member as a science buddy',
      'Members review lay abstracts and specific aims for their assigned research programme',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['The programme began in 2025. The page does not say whether members are paid.'],
  },
  {
    key: 'karmanos-byc-curriculum',
    title: 'Building Your Capacity (BYC) Research Training Curriculum',
    organization: 'Karmanos Cancer Institute',
    institution: 'Karmanos Cancer Institute',
    url: 'https://www.karmanos.org/karmanos/building-your-capacity-byc-research-training-curri',
    city: 'Detroit',
    summary:
      'A nine-module course teaching community members the basics of research — developing research questions, data collection methods and research ethics — as a route to community advisory boards or to becoming a community co-investigator on a funded project.',
    field: 'Research methods training',
    disciplines: ['research methods', 'research ethics', 'community-based participatory research'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Open to community members; no prior research experience required',
      'Nine modules covering research questions, data collection methods and research ethics',
      'Two cohorts are planned for 2026',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'annual_academic_year',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['The page names two 2026 cohorts but gives no dates on the part we can read; confirm the cohort calendar before demo.'],
  },
  {
    key: 'karmanos-k-raise',
    title: 'K-RAISE Medical Student Research and Mentorship Program',
    organization: 'Karmanos Cancer Institute',
    institution: 'Karmanos Cancer Institute',
    url: 'https://www.karmanos.org/karmanos/k-raise',
    city: 'Detroit',
    summary:
      'Medical students join oncology research with monthly journal clubs alongside oncology fellows, institutional didactics, a multidisciplinary team symposium and professional development workshops on research design and abstract writing.',
    field: 'Oncology',
    disciplines: ['oncology', 'clinical research', 'medical education'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Medical students', 'Includes journal clubs, institutional didactics and professional development workshops'],
    minEducation: 'bachelor',
    enrollmentRequired: 'graduate',
    citizenship: 'unstated',
    isPaid: true,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'contact_program',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: ['The page says "Stipends for participants" without an amount.'],
  },
  {
    key: 'karmanos-path',
    title: 'PATH: Preparing Aspiring Translational Hematology/Oncology Fellows',
    organization: 'Karmanos Cancer Institute',
    institution: 'Karmanos Cancer Institute',
    url: 'https://www.karmanos.org/karmanos/path-program',
    city: 'Detroit',
    summary:
      'A structured ten-week translational research programme for oncology fellows: mentor matching and lab onboarding, then preclinical experiments and correlative assays, then data interpretation, an abstract and a final institutional presentation.',
    field: 'Translational hematology and oncology',
    disciplines: ['hematology', 'oncology', 'translational research'],
    stipendUsd: null,
    durationWeeks: 10,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Limited to current U.S. GME fellows in oncology or closely related specialties',
      'Third-year fellows are especially encouraged, having the most protected research time',
    ],
    minEducation: 'postgraduate',
    enrollmentRequired: 'postdoc',
    citizenship: 'us_work_authorized',
    isPaid: null,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'contact_program',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: [
      'The $3,000-$4,000 figure on this page is a per-fellow lab expense budget for reagents and assays, not pay. stipendUsd is deliberately null.',
    ],
  },
  {
    key: 'karmanos-education-training',
    title: 'Karmanos education and research training programs',
    organization: 'Karmanos Cancer Institute',
    institution: 'Karmanos Cancer Institute',
    url: 'https://www.karmanos.org/karmanos/education-and-research-training-karmanos',
    city: 'Detroit',
    summary:
      'The index of every Karmanos research training route, from middle and high school programs through undergraduate fellowships to graduate and fellow-level training. The place to start if none of the individual listings fit.',
    field: 'Cancer research training',
    disciplines: ['cancer research', 'biomedical science', 'medical physics'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Programs range from grade 10 through postdoctoral fellows; each has its own requirements'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: false,
    lowBarrier: true,
    factsFrom: 'program_page',
  },

  // ---- Henry Ford Health --------------------------------------------------------
  {
    key: 'hfh-surgery-high-school-mentorship',
    title: 'Department of Surgery High School Mentorship summer internship',
    organization: 'Henry Ford Health',
    institution: 'Henry Ford Health',
    url: 'https://www.henryford.com/hcp/med-ed/surgery-mentorship/summer-internship',
    city: 'Detroit',
    summary:
      'A seven-week paid summer internship that pairs a high school student one-to-one with a professional mentor in surgery, the culminating phase of a free three-part mentorship programme.',
    field: 'Surgery and clinical research',
    disciplines: ['surgery', 'medicine', 'clinical research'],
    stipendUsd: 1000,
    durationWeeks: 7,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'High school students',
      'Free to take part; a $1,000 stipend is paid to each intern',
      'Interns are paired one-to-one with a professional mentor aligned to their interests',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'high_school',
    citizenship: 'unstated',
    isPaid: true,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['Highly competitive: the page reports 331 applications for 25 places in 2025. The page carries no application deadline.'],
  },
  {
    key: 'hfh-hdrc-trainees',
    title: 'Health Disparities Research Collaborative scholars and trainees',
    organization: 'Henry Ford Health Public Health Sciences',
    institution: 'Henry Ford Health',
    url: 'https://www.henryford.com/hcp/research/public-population-research/hdrc/hdrc-interns-and-trainees',
    city: 'Detroit',
    summary:
      'Student placements in Henry Ford\'s Public Health Sciences department working on health disparities and epidemiology, including the NIH-funded BUILD undergraduate program run with the University of Detroit Mercy and Wayne State, and an HBCU partnership internship.',
    field: 'Public health and health disparities',
    disciplines: ['public health', 'epidemiology', 'health disparities', 'population health'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Undergraduate and graduate students; routes differ by programme',
      'BUILD is an NIH-funded undergraduate program aimed at increasing the number of underrepresented students on the path to becoming scientific researchers',
      'The HFH and JSU partnership places students with Henry Ford physicians and researchers for four weeks',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'contact_program',
    recurrence: 'annual_summer',
    communityBased: true,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: ['The page is mostly past trainee profiles; it names the programmes but gives no current dates, stipends or deadlines.'],
  },
  {
    key: 'hfh-research-home',
    title: 'Henry Ford Health research',
    organization: 'Henry Ford Health',
    institution: 'Henry Ford Health',
    url: 'https://www.henryford.com/hcp/research',
    city: 'Detroit',
    summary:
      'The front door to research at one of Detroit\'s largest health systems, covering the research institute, its centres and the departments that run clinical and population studies.',
    field: 'Health systems research',
    disciplines: ['clinical research', 'population health', 'health services research'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['A hub page; individual roles and training programmes have their own requirements'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: false,
    lowBarrier: true,
    factsFrom: 'program_page',
  },
  {
    key: 'hfh-student-internships',
    title: 'Henry Ford Health student internships and apprenticeships',
    organization: 'Henry Ford Health',
    institution: 'Henry Ford Health',
    url: 'https://henryford.referrals.selectminds.com/landingpages/student-internships-apprenticeships-12',
    city: 'Detroit',
    summary:
      'The health system\'s own board of student internships and apprenticeships, where its paid summer research, public health and cancer institute internships are posted as they open.',
    field: 'Health systems research',
    disciplines: ['clinical research', 'public health', 'cancer research', 'health policy'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Requirements are set per posting; postings appear and close through the year'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'us_work_authorized',
    isPaid: true,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'job_board',
    recurrence: 'rolling',
    communityBased: false,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['A board, not a single opening. Individual postings churn too fast to record here; the board URL is the stable thing.'],
  },

  // ---- Corewell Health -----------------------------------------------------------
  {
    key: 'corewell-student-opportunities',
    title: 'Corewell Health student internships',
    organization: 'Corewell Health',
    institution: 'Corewell Health',
    url: 'https://careers.corewellhealth.org/us/en/student',
    city: 'Royal Oak',
    summary:
      'Paid internships at Michigan\'s largest integrated health system, open to undergraduate and graduate students. Most are summer placements, posted on the careers board between October and March.',
    field: 'Health systems research',
    disciplines: ['clinical research', 'health administration', 'public health'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Open to undergraduate or graduate students',
      'Most paid internships are in summer, posted between October and March',
      'Search the careers page for "internship" and set up a search agent for alerts',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'us_work_authorized',
    isPaid: true,
    mentorshipModel: 'clinical_team',
    applicationMethod: 'job_board',
    recurrence: 'annual_summer',
    nextWindowOpens: '2026-10-01',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: [
      'The GROWTH internship on the same page is restricted to Benton Harbor and Niles residents, so it is not a metro Detroit opportunity and is deliberately not listed separately.',
    ],
  },

  // ---- Oakland University ---------------------------------------------------------
  {
    key: 'ou-uncore-cyberai',
    title: 'NSF REU Site: Undergraduate Computer Research in Cybersecurity and AI (UnCoRe-CyberAI)',
    organization: 'Oakland University Computer Science and Engineering',
    institution: 'Oakland University',
    url: 'https://cse-reu.secs.oakland.edu/index.php?site=about',
    city: 'Rochester',
    summary:
      'A ten-week full-time summer research programme in cybersecurity and AI, running for over a decade. Ten students a year work with faculty mentors on problems of national priority, with a stipend, meal allowance and travel subsidy.',
    field: 'Cybersecurity and artificial intelligence',
    disciplines: ['cybersecurity', 'artificial intelligence', 'computer science', 'computer engineering'],
    stipendUsd: 7000,
    durationWeeks: 10,
    startsAt: null,
    applyBy: '2026-02-28',
    eligibility: [
      'Open to all non-graduating undergraduate students',
      'U.S. citizens and permanent residents only',
      'An interest in computer science and engineering',
      'Students cannot be working or taking classes at the same time',
      'Housing subsidy provided for students staying on campus',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'us_citizen_or_pr',
    isPaid: true,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    nsfAwardId: '2349663',
  },
  {
    key: 'ou-aerim-reu',
    title: 'NSF REU Site: Automotive and Energy Research and Industrial Mentorship (AERIM)',
    organization: 'Oakland University School of Engineering and Computer Science',
    institution: 'Oakland University',
    url: 'https://sites.google.com/oakland.edu/aerim-reu/home',
    city: 'Rochester',
    summary:
      'Ten weeks of summer research on automotive and clean-energy projects, with one-to-one contact with faculty, industrial mentors and graduate students, plus field trips and outreach work.',
    field: 'Automotive and energy engineering',
    disciplines: ['mechanical engineering', 'automotive engineering', 'clean energy'],
    stipendUsd: null,
    durationWeeks: 10,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Undergraduate engineering, science or math students',
      'Freshmen, undeclared majors and community college students are welcome to apply',
      'An interest in automotive and clean-energy research topics',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: true,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: [
      'Community college students are explicitly welcome, which is rarer than it should be among REU sites.',
      'Check whether the site is running a given summer before promoting it; it has skipped at least one year.',
    ],
  },
  {
    key: 'ou-secs-research-opportunities',
    title: 'Oakland University engineering undergraduate research opportunities',
    organization: 'Oakland University School of Engineering and Computer Science',
    institution: 'Oakland University',
    url: 'https://www.oakland.edu/secs/student-resources/research-opportunities/',
    city: 'Rochester',
    summary:
      'The school\'s running list of undergraduate research routes: the NSF REU sites it hosts, hourly paid student research assistant positions, and paid undergraduate internships of around 20 hours a week.',
    field: 'Engineering and computer science',
    disciplines: ['computer science', 'cybersecurity', 'electrical engineering', 'mechanical engineering'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Undergraduate students in CS, IT, AI, cybersecurity, EE, CE or computing-related fields',
      'Paid hourly student research assistant positions are listed alongside the REU sites',
      'Undergraduate internships run about 20 hours a week at the university student rate',
    ],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: true,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
  },

  // ---- Detroit Urban Research Center ------------------------------------------------
  {
    key: 'detroit-urc-cbpr-academy',
    title: 'CBPR Partnership Academy',
    organization: 'Detroit Community-Academic Urban Research Center',
    institution: 'Detroit Urban Research Center',
    url: 'https://www.detroiturc.org/programs-expertise/cbpr-partnership-academy',
    city: 'Detroit',
    summary:
      'A year-long capacity-building programme in community-based participatory research, run by experienced community and academic partners. Twelve two-person teams are selected per cohort, each pairing a community partner with an academic one.',
    field: 'Community-based participatory research',
    disciplines: ['community-based participatory research', 'public health', 'health equity'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Applications are made as a two-person team: one community partner and one academic partner',
      'Twelve teams are selected per cohort through competitive review',
      'Includes attendance at a week-long intensive course',
      'Partnership development, grant proposal preparation, mentoring and online learning forums follow',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'online_form',
    recurrence: 'annual_academic_year',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['The community partner side of a team does not need an academic background, which is what makes this a genuine low-barrier route into research.'],
  },
  {
    key: 'detroit-urc-car-net',
    title: 'Community-Academic Research Network (CAR-Net)',
    organization: 'Detroit Community-Academic Urban Research Center',
    institution: 'Detroit Urban Research Center',
    url: 'https://www.detroiturc.org/programs-expertise/community-academic-research-network',
    city: 'Detroit',
    summary:
      'A standing network joining Detroit community organisations to academic researchers who want to run and share collaborative research in the city, with scholarships for community organisations to take a week-long CBPR short course.',
    field: 'Community-based participatory research',
    disciplines: ['community-based participatory research', 'public health', 'health equity'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Open to Detroit community organisations and to academic researchers',
      'Scholarships are available for community organisations to attend a week-long CBPR short course',
      'The short course runs as EPID 783 in the U-M School of Public Health Graduate Summer Session in Epidemiology',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
  },

  // ---- Environmental and community science --------------------------------------------
  {
    key: 'ecology-center-air-monitoring',
    title: 'Community-Based Air Monitoring Network',
    organization: 'Ecology Center',
    institution: 'Ecology Center',
    url: 'https://www.ecocenter.org/our-work/community-based-science/community-based-air-monitoring-network',
    city: 'Detroit',
    summary:
      'Residents and schools run low-cost air monitors across Detroit and Wayne County and read the data themselves, through the Air Sensor Learning Collaborative of community, government and academic partners.',
    field: 'Environmental health',
    disciplines: ['air quality', 'environmental justice', 'community science', 'data collection'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Open to residents, schools and community organisations in Detroit and Wayne County',
      'No scientific background required',
      'Current Detroit school partners include the Grace Lee Boggs School, University Prep Academy High School and Clippert Multicultural Magnet Honors Academy',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['The page does not say whether participants are paid; treat as unpaid community science until confirmed.'],
  },
  {
    key: 'green-door-environmental-technician',
    title: 'Environmental Technician workforce training',
    organization: 'Green Door Initiative',
    institution: 'Green Door Initiative',
    url: 'https://www.greendoorinitiative.org/',
    city: 'Detroit',
    summary:
      'Detroit\'s flagship route into environmental monitoring work: training towards licensed Environmental Technician credentials, with field sampling and data collection skills. Explicitly open to returning citizens and applicants with felony or misdemeanour records.',
    field: 'Environmental monitoring',
    disciplines: ['environmental science', 'environmental justice', 'field sampling', 'air quality'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: [
      'Students of all backgrounds are encouraged to apply',
      'Returning citizens and applicants with felony and misdemeanour backgrounds are supported and not discriminated against',
      'Graduates become licensed environmental technicians',
    ],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'online_form',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: [
      'This is workforce training that leads into environmental data collection rather than a research post as such. Listed because environmental monitoring is the realistic entry point into environmental justice research in Detroit.',
    ],
  },
  {
    key: 'scistarter-citizen-science',
    title: 'Citizen science projects needing volunteers',
    organization: 'SciStarter',
    institution: 'SciStarter',
    url: 'https://www.scistarter.org/',
    city: null,
    isOnline: true,
    summary:
      'A searchable catalogue of active research projects that need members of the public to collect or classify data, filterable by topic and by whether the work is done outdoors or online. No qualification of any kind is required to join one.',
    field: 'Citizen science',
    disciplines: ['citizen science', 'data collection', 'ecology', 'astronomy', 'public health'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Open to anyone', 'Most projects are unpaid volunteer contributions to real research'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'open',
    isPaid: false,
    mentorshipModel: 'self_directed',
    applicationMethod: 'online_form',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['National rather than Detroit-specific, and unpaid. Included because it is the only route on this list with no barrier at all.'],
  },

  // ---- Community health worker routes ---------------------------------------------------
  {
    key: 'michwa-chw-pathway',
    title: 'Community Health Worker certification pathway',
    organization: 'Michigan Community Health Worker Alliance',
    institution: 'Michigan Community Health Worker Alliance',
    url: 'https://michwa.org/',
    city: null,
    summary:
      'The statewide body that sets and recognises Community Health Worker training in Michigan. CHW certification is the usual way into the paid community data-collection and study-support roles that Detroit health research runs on.',
    field: 'Community health',
    disciplines: ['community health', 'public health', 'health equity'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['No degree required', 'Training requirements and approved programmes are set by the alliance'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'us_work_authorized',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
    notes: ['A pathway rather than a single opening. Listed because CHW roles are the most realistic paid research-adjacent work for a Detroiter with no degree.'],
  },
  {
    key: 'detroit-recovery-chw-training',
    title: 'Community Health Worker Training Program',
    organization: 'Detroit Recovery Project',
    institution: 'Detroit Recovery Project',
    url: 'https://www.recovery4detroit.com/rti/chwtp-program/',
    city: 'Detroit',
    summary:
      'Detroit-based Community Health Worker training run by a recovery organisation, aimed at people from the communities the work serves and leading into paid outreach and study-support roles.',
    field: 'Community health',
    disciplines: ['community health', 'behavioural health', 'recovery support'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['No degree required; see the programme page for current cohort requirements'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'us_work_authorized',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'program_page',
  },

  // ---- Lawrence Technological University ----------------------------------------------
  // Surfaced by the NIH coverage audit: Southfield is in the metro region, LTU
  // holds live NIH biomedical engineering funding, and nothing here listed a way in.
  {
    key: 'ltu-research',
    title: 'Lawrence Tech research and student opportunities',
    organization: 'Lawrence Technological University',
    institution: 'Lawrence Technological University',
    url: 'https://ltu.edu/research/',
    city: 'Southfield',
    summary:
      'Research across architecture and design, arts and sciences, business and IT, engineering and health sciences at Southfield\'s technological university, with routes in for graduate students and a high school summer programme.',
    field: 'Engineering and applied science',
    disciplines: ['engineering', 'biomedical engineering', 'computer science', 'architecture'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Routes differ by college; the page signposts graduate students and high school summer programmes'],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'program_page',
    notes: [
      'A divisional hub rather than a single programme; the page lists no dates, stipends or deadlines. Added because the NIH coverage audit flagged Lawrence Tech as a funded institution with no way in listed.',
    ],
  },

  // ---- University of Michigan and Eastern Michigan ----------------------------------------
  // umich.edu and emich.edu answer an automated request with a Cloudflare
  // challenge, so these pages cannot be read by the pipeline. The urls are real
  // and were confirmed to be challenged rather than missing; every fact the page
  // would have carried is left null rather than guessed. Anyone with a browser
  // can fill these in, and the run report lists them every time.
  {
    key: 'umich-srop',
    title: 'Summer Research Opportunity Program (SROP)',
    organization: 'Rackham Graduate School, University of Michigan',
    institution: 'University of Michigan',
    url: 'https://rackham.umich.edu/prospective-students/srop/',
    city: 'Ann Arbor',
    summary:
      'Rackham\'s summer research programme for undergraduates considering a PhD, pairing them with U-M faculty. Application materials for the following summer are published in the autumn.',
    field: 'Doctoral preparation',
    disciplines: ['interdisciplinary', 'graduate preparation'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Undergraduate students considering doctoral study'],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'unverified',
    notes: ['umich.edu serves a Cloudflare challenge to robots, so no fact on this entry has been read off the page. Stipend, dates and deadline must be filled in by a human before demo.'],
  },
  {
    key: 'umich-urop',
    title: 'Undergraduate Research Opportunity Program (UROP)',
    organization: 'University of Michigan LSA',
    institution: 'University of Michigan',
    url: 'https://lsa.umich.edu/urop',
    city: 'Ann Arbor',
    summary:
      'U-M\'s long-running programme placing undergraduates on faculty research projects during the academic year and over the summer, across every division of the university.',
    field: 'Any discipline',
    disciplines: ['interdisciplinary', 'sciences', 'social sciences', 'humanities'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Enrolled University of Michigan undergraduates'],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_academic_year',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'unverified',
    notes: ['Cloudflare-challenged; no facts read off the page.'],
  },
  {
    key: 'umich-michr',
    title: 'Michigan Institute for Clinical and Health Research (MICHR)',
    organization: 'University of Michigan',
    institution: 'University of Michigan',
    url: 'https://michr.umich.edu/',
    city: 'Ann Arbor',
    summary:
      'U-M\'s clinical and translational research institute, which runs training, pilot funding and community engagement programmes for people entering clinical research.',
    field: 'Clinical and translational research',
    disciplines: ['clinical research', 'translational research', 'community engagement'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Programmes range from community partners through to faculty; each has its own requirements'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'unverified',
    notes: ['Cloudflare-challenged; no facts read off the page.'],
  },
  {
    key: 'umich-sph-summer-enrichment',
    title: 'Summer Enrichment Program in Health Management and Policy',
    organization: 'University of Michigan School of Public Health',
    institution: 'University of Michigan',
    url: 'https://sph.umich.edu/admissions/summer-enrichment-program.html',
    city: 'Ann Arbor',
    summary:
      'A summer programme introducing students from underrepresented backgrounds to health management and policy research and practice, run out of the School of Public Health.',
    field: 'Health policy and management',
    disciplines: ['health policy', 'health management', 'public health'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['See the programme page; requirements have not been read'],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'cohort_program',
    applicationMethod: 'online_form',
    recurrence: 'annual_summer',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'unverified',
    notes: ['Cloudflare-challenged; no facts read off the page.'],
  },
  {
    key: 'umich-detroit-center',
    title: 'U-M Detroit Center community-engaged research',
    organization: 'University of Michigan Detroit Center',
    institution: 'University of Michigan',
    url: 'https://detroit.umich.edu/',
    city: 'Detroit',
    summary:
      'U-M\'s Detroit base for community-engaged projects, and the front door to its Detroit partnerships including the Detroit Urban Research Center.',
    field: 'Community-engaged research',
    disciplines: ['community-engaged research', 'urban studies', 'public health'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Varies by project'],
    minEducation: 'none_required',
    enrollmentRequired: 'none',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'community_partnership',
    applicationMethod: 'contact_program',
    recurrence: 'rolling',
    communityBased: true,
    lowBarrier: true,
    factsFrom: 'unverified',
    notes: ['Cloudflare-challenged; no facts read off the page.'],
  },
  {
    key: 'emich-undergraduate-research',
    title: 'Undergraduate Research Program',
    organization: 'Eastern Michigan University',
    institution: 'Eastern Michigan University',
    url: 'https://www.emich.edu/undergraduate-research/',
    city: 'Ypsilanti',
    summary:
      'Eastern Michigan\'s undergraduate research office, which funds and places students on faculty-mentored projects. The nearest research university to Detroit\'s western suburbs after U-M.',
    field: 'Any discipline',
    disciplines: ['interdisciplinary'],
    stipendUsd: null,
    durationWeeks: null,
    startsAt: null,
    applyBy: null,
    eligibility: ['Enrolled Eastern Michigan undergraduates'],
    minEducation: 'secondary',
    enrollmentRequired: 'undergraduate',
    citizenship: 'unstated',
    isPaid: null,
    mentorshipModel: 'faculty_lab',
    applicationMethod: 'online_form',
    recurrence: 'annual_academic_year',
    communityBased: false,
    lowBarrier: false,
    factsFrom: 'unverified',
    notes: ['Cloudflare-challenged; no facts read off the page.'],
  },
];
